<template><div><div class="flex-between mb-16"><h3>渠道管理</h3><el-button type="primary" @click="openDialog()">+ 新增渠道</el-button></div><el-alert title="仅保留 OpenAI、DeepSeek、Anthropic 三个官方渠道；同步模型时会自动过滤其他厂商模型。" type="info" :closable="false" style="margin-bottom:16px"/>
<el-table :data="channels" stripe v-loading="loading"><el-table-column prop="channel_name" label="官方渠道" width="150"/><el-table-column prop="base_url" label="上游地址" min-width="260"/><el-table-column label="状态" width="80"><template #default="{row}"><el-tag :type="row.status==='active'?'success':'danger'" size="small">{{ row.status }}</el-tag></template></el-table-column><el-table-column prop="priority" label="优先级" width="80"/><el-table-column label="健康状态" width="110"><template #default="{row}"><el-tag :type="healthType(row)" size="small">{{ healthLabel(row) }}</el-tag></template></el-table-column><el-table-column label="操作" width="290"><template #default="{row}"><el-button size="small" @click="openDialog(row)">编辑</el-button><el-button size="small" type="primary" plain :loading="syncingId===row.id" @click="syncModels(row)">同步模型</el-button><el-button size="small" :type="row.status==='active'?'warning':'success'" @click="toggle(row)">{{ row.status==='active'?'停用':'启用' }}</el-button></template></el-table-column></el-table>
<el-dialog v-model="dialogVisible" :title="isEdit?'编辑渠道':'新增渠道'" width="480px"><el-form :model="form" label-width="100px"><el-form-item label="官方渠道"><el-select v-model="form.channel_name" :disabled="isEdit"><el-option value="openai" label="OpenAI"/><el-option value="deepseek" label="DeepSeek"/><el-option value="anthropic" label="Anthropic"/></el-select></el-form-item><el-form-item label="上游地址"><el-input v-model="form.base_url"/></el-form-item><el-form-item label="API Key"><el-input v-model="form.api_key" type="password" show-password :placeholder="isEdit?'已配置（留空不修改）':'请输入 API Key'"/></el-form-item><el-form-item label="优先级"><el-input-number v-model="form.priority" :min="0"/></el-form-item><el-form-item label="权重"><el-input-number v-model="form.weight" :min="0" :max="1000"/></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></div></template>
<script setup>
import { ref, onMounted } from 'vue';import api from '@/api';import { ElMessage } from 'element-plus'
const channels=ref([]),loading=ref(false),dialogVisible=ref(false),isEdit=ref(false),saving=ref(false),syncingId=ref(null),originalApiKey=ref('')
const empty=()=>({channel_name:'openai',base_url:'',api_key:'',priority:0,weight:100});const form=ref(empty());onMounted(fetch)
async function fetch(){loading.value=true;try{channels.value=(await api.get('/api/admin/channels')).data.data}catch(e){}loading.value=false}
function openDialog(row){isEdit.value=!!row;form.value=row?{...row}:empty();originalApiKey.value=row?.api_key||'';dialogVisible.value=true}
async function save(){saving.value=true;try{const data={...form.value};if(isEdit.value&&data.api_key===originalApiKey.value)data.api_key='';if(isEdit.value)await api.put(`/api/admin/channels/${data.id}`,data);else await api.post('/api/admin/channels',data);ElMessage.success('保存成功');dialogVisible.value=false;fetch()}catch(e){}saving.value=false}
async function toggle(row){await api.patch(`/api/admin/channels/${row.id}/status`,{status:row.status==='active'?'inactive':'active'});ElMessage.success('操作成功');fetch()}
async function syncModels(row){syncingId.value=row.id;try{const r=await api.post(`/api/admin/channels/${row.id}/sync-models`);ElMessage.success(r.data.message);fetch()}catch(e){}syncingId.value=null}
function healthType(r){return r.status!=='active'?'info':(r.health_score||100)>=60?'success':'warning'}function healthLabel(r){return r.status!=='active'?'未启用':(r.health_score||100)>=60?'在线':'降级'}
</script>
