<template><div class="admin-page pricing-page"><div class="flex-between mb-16"><h3>用户扣费倍率</h3><el-button type="primary" @click="openDialog()">+ 新增规则</el-button></div>
<el-alert title="模型留空表示全局规则，会应用到所有保留模型；用户看到的倍率与实际扣点完全一致。" type="info" :closable="false" style="margin-bottom:16px"/>
<el-table :data="rules" stripe v-loading="loading"><el-table-column prop="rule_name" label="规则名称" min-width="150"/><el-table-column label="适用模型" width="160"><template #default="{row}">{{ row.model_code||'全部模型' }}</template></el-table-column><el-table-column label="作用范围" width="150"><template #default="{row}"><el-tag size="small">{{ scl(row.scope_type) }}</el-tag><span v-if="row.scope_id"> ID:{{ row.scope_id }}</span></template></el-table-column><el-table-column label="用户扣费倍率(入/出/图)" width="220"><template #default="{row}">×{{ row.billing_multiplier_input }} / ×{{ row.billing_multiplier_output }} / ×{{ row.billing_multiplier_image }}</template></el-table-column><el-table-column label="优先级" width="80" prop="priority"/><el-table-column label="状态" width="80"><template #default="{row}"><el-tag :type="row.status==='active'?'success':'info'" size="small">{{ row.status }}</el-tag></template></el-table-column><el-table-column label="操作" width="160"><template #default="{row}"><el-button size="small" @click="openDialog(row)">编辑</el-button><el-popconfirm title="确定删除？" @confirm="delRule(row.id)"><template #reference><el-button size="small" type="danger">删除</el-button></template></el-popconfirm></template></el-table-column></el-table>
<el-dialog v-model="dialogVisible" :title="isEdit?'编辑规则':'新增规则'" width="560px"><el-form :model="form" label-width="130px"><el-form-item label="规则名称"><el-input v-model="form.rule_name"/></el-form-item><el-form-item label="适用模型"><el-input v-model="form.model_code" placeholder="留空=全部模型"/></el-form-item><el-form-item label="作用范围"><el-select v-model="form.scope_type"><el-option value="platform" label="平台默认"/><el-option value="user" label="单个用户"/></el-select></el-form-item><el-form-item v-if="form.scope_type==='user'" label="用户 ID"><el-input-number v-model="form.scope_id" :min="1"/></el-form-item><el-form-item label="用户扣费倍率(输入)"><el-input-number v-model="form.multiplier_input" :min="0.0001" :step="0.1"/></el-form-item><el-form-item label="用户扣费倍率(输出)"><el-input-number v-model="form.multiplier_output" :min="0.0001" :step="0.1"/></el-form-item><el-form-item label="用户扣费倍率(图片)"><el-input-number v-model="form.multiplier_image" :min="0.0001" :step="0.1"/></el-form-item><el-form-item label="优先级"><el-input-number v-model="form.priority" :min="0" :max="999"/></el-form-item><el-form-item label="状态"><el-switch v-model="form.status" active-value="active" inactive-value="inactive"/></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></div></template>
<script setup>
import { ref, onMounted } from 'vue';import api from '@/api';import { ElMessage } from 'element-plus'
const rules=ref([]),loading=ref(false),dialogVisible=ref(false),isEdit=ref(false),saving=ref(false)
const empty=()=>({rule_name:'',model_code:'',scope_type:'platform',scope_id:null,multiplier_input:1,multiplier_output:1,multiplier_image:1,priority:0,status:'active'})
const form=ref(empty());onMounted(fetchRules)
async function fetchRules(){loading.value=true;try{rules.value=(await api.get('/api/admin/pricing-rules')).data.data}catch(e){}loading.value=false}
function openDialog(row){isEdit.value=!!row;form.value=row?{...row,multiplier_input:row.billing_multiplier_input,multiplier_output:row.billing_multiplier_output,multiplier_image:row.billing_multiplier_image||1}:empty();dialogVisible.value=true}
async function save(){saving.value=true;try{if(isEdit.value)await api.put(`/api/admin/pricing-rules/${form.value.id}`,form.value);else await api.post('/api/admin/pricing-rules',form.value);ElMessage.success('保存成功');dialogVisible.value=false;fetchRules()}catch(e){}saving.value=false}
async function delRule(id){await api.delete(`/api/admin/pricing-rules/${id}`);ElMessage.success('已删除');fetchRules()}
function scl(s){return {platform:'平台默认',user:'单用户'}[s]||s}
</script>
