BEGIN;

-- 控制面：管理员、模型目录、定价、全局配置与支付开关。
CREATE TABLE IF NOT EXISTS staff_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'operator', 'finance', 'support')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS models (
  model_code TEXT PRIMARY KEY,
  model_name TEXT NOT NULL,
  provider TEXT NOT NULL DEFAULT '',
  model_type TEXT NOT NULL DEFAULT 'llm',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pricing_rules (
  rule_key TEXT PRIMARY KEY,
  model_code TEXT REFERENCES models(model_code),
  billing_mode TEXT NOT NULL DEFAULT 'token',
  rule JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_config (
  config_key TEXT PRIMARY KEY,
  config_value JSONB NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_providers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_code TEXT NOT NULL UNIQUE,
  provider_name TEXT NOT NULL,
  provider_type TEXT NOT NULL,
  config JSONB NOT NULL DEFAULT '{}'::jsonb,
  secret_envelope TEXT,
  secret_version TEXT,
  status TEXT NOT NULL DEFAULT 'disabled' CHECK (status IN ('disabled', 'active')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 账号池：上游凭据只存版本化 AES-GCM 密文，不存明文。
CREATE TABLE IF NOT EXISTS upstream_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_key TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  base_url TEXT NOT NULL,
  protocol_type TEXT NOT NULL DEFAULT 'openai_compatible',
  api_key_envelope TEXT NOT NULL,
  secret_version TEXT NOT NULL,
  capabilities JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'error')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS account_models (
  account_id BIGINT NOT NULL REFERENCES upstream_accounts(id) ON DELETE CASCADE,
  model_code TEXT NOT NULL REFERENCES models(model_code) ON DELETE CASCADE,
  upstream_model_name TEXT NOT NULL,
  supports_image_input BOOLEAN NOT NULL DEFAULT FALSE,
  configuration JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  PRIMARY KEY (account_id, model_code)
);

CREATE TABLE IF NOT EXISTS routing_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_key TEXT NOT NULL UNIQUE,
  group_name TEXT NOT NULL,
  protocol_type TEXT NOT NULL DEFAULT 'openai_compatible',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  configuration JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS routing_group_accounts (
  routing_group_id BIGINT NOT NULL REFERENCES routing_groups(id) ON DELETE CASCADE,
  account_id BIGINT NOT NULL REFERENCES upstream_accounts(id) ON DELETE CASCADE,
  priority INTEGER NOT NULL DEFAULT 0,
  weight INTEGER NOT NULL DEFAULT 100 CHECK (weight > 0),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  PRIMARY KEY (routing_group_id, account_id)
);

CREATE TABLE IF NOT EXISTS routing_group_models (
  routing_group_id BIGINT NOT NULL REFERENCES routing_groups(id) ON DELETE CASCADE,
  model_code TEXT NOT NULL REFERENCES models(model_code) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  billing_multiplier NUMERIC(18, 6),
  PRIMARY KEY (routing_group_id, model_code)
);

-- 用户面：普通用户与其支付、余额和 API Key 数据独立于控制面导入。
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin', 'operator', 'finance')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  key_name TEXT NOT NULL DEFAULT '',
  key_hash TEXT NOT NULL UNIQUE,
  key_prefix TEXT NOT NULL,
  key_envelope TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled', 'revoked')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_used_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS api_key_permissions (
  api_key_id BIGINT NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
  model_code TEXT NOT NULL REFERENCES models(model_code),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  PRIMARY KEY (api_key_id, model_code)
);

CREATE TABLE IF NOT EXISTS wallets (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  quota_balance NUMERIC(18, 6) NOT NULL DEFAULT 0 CHECK (quota_balance >= 0),
  gift_quota NUMERIC(18, 6) NOT NULL DEFAULT 0 CHECK (gift_quota >= 0),
  frozen_balance NUMERIC(18, 6) NOT NULL DEFAULT 0 CHECK (frozen_balance >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wallet_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  transaction_key TEXT NOT NULL UNIQUE,
  transaction_type TEXT NOT NULL,
  amount NUMERIC(18, 6) NOT NULL,
  balance_after NUMERIC(18, 6),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quota_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_key TEXT NOT NULL UNIQUE,
  user_id BIGINT NOT NULL REFERENCES users(id),
  payment_provider_id BIGINT REFERENCES payment_providers(id),
  amount NUMERIC(18, 6) NOT NULL CHECK (amount > 0),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'cancelled', 'expired', 'refunded')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 请求日志按 created_at 自然月分区；唯一性包含分区键，避免全局索引假设。
CREATE TABLE IF NOT EXISTS api_request_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  request_id TEXT NOT NULL,
  user_id BIGINT REFERENCES users(id),
  api_key_id BIGINT REFERENCES api_keys(id),
  model_code TEXT,
  upstream_account_id BIGINT REFERENCES upstream_accounts(id),
  status TEXT NOT NULL,
  latency_ms INTEGER NOT NULL DEFAULT 0,
  input_tokens BIGINT NOT NULL DEFAULT 0,
  output_tokens BIGINT NOT NULL DEFAULT 0,
  total_cost NUMERIC(18, 6) NOT NULL DEFAULT 0,
  billing_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE INDEX IF NOT EXISTS idx_api_request_logs_request_id ON api_request_logs (request_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_api_request_logs_user_created ON api_request_logs (user_id, created_at DESC);

CREATE OR REPLACE FUNCTION ensure_api_request_logs_partition(partition_month DATE)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
  month_start DATE := date_trunc('month', partition_month)::date;
  month_end DATE := (date_trunc('month', partition_month) + INTERVAL '1 month')::date;
  partition_name TEXT := format('api_request_logs_%s', to_char(partition_month, 'YYYY_MM'));
BEGIN
  IF partition_month <> month_start THEN
    RAISE EXCEPTION 'partition month must be the first day of the month';
  END IF;
  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS %I PARTITION OF api_request_logs FOR VALUES FROM (%L) TO (%L)',
    partition_name, month_start, month_end
  );
END;
$$;

SELECT ensure_api_request_logs_partition(date_trunc('month', CURRENT_DATE)::date);
SELECT ensure_api_request_logs_partition((date_trunc('month', CURRENT_DATE) + INTERVAL '1 month')::date);

CREATE TABLE IF NOT EXISTS user_daily_usage (
  usage_date DATE NOT NULL,
  user_id BIGINT NOT NULL REFERENCES users(id),
  model_code TEXT NOT NULL,
  request_count BIGINT NOT NULL DEFAULT 0,
  input_tokens BIGINT NOT NULL DEFAULT 0,
  output_tokens BIGINT NOT NULL DEFAULT 0,
  total_cost NUMERIC(18, 6) NOT NULL DEFAULT 0,
  PRIMARY KEY (usage_date, user_id, model_code)
);

CREATE TABLE IF NOT EXISTS platform_daily_usage (
  usage_date DATE NOT NULL,
  model_code TEXT NOT NULL,
  request_count BIGINT NOT NULL DEFAULT 0,
  input_tokens BIGINT NOT NULL DEFAULT 0,
  output_tokens BIGINT NOT NULL DEFAULT 0,
  total_cost NUMERIC(18, 6) NOT NULL DEFAULT 0,
  PRIMARY KEY (usage_date, model_code)
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  audit_key TEXT NOT NULL UNIQUE,
  action TEXT NOT NULL,
  actor_staff_user_id BIGINT REFERENCES staff_users(id),
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO system_config (config_key, config_value, description)
VALUES ('payment_enabled', 'false'::jsonb, '在线支付总开关；基础迁移默认关闭')
ON CONFLICT (config_key) DO NOTHING;

INSERT INTO schema_migrations (version, checksum)
VALUES ('001_foundation', 'postgres-foundation-v1')
ON CONFLICT (version) DO NOTHING;

COMMIT;
